### ISSUE TITLE
Sett opp pre-commit hooks

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-api#10]
- [ ] Ikke tillat innsjekking av kode som ikke validerer i lint
- [ ] Ikke tillat innsjekking av kode hvor ikke e2e og unit kjører suksessfullt

**Comment by kennethlynne** [comment]
Er det lagt inn e2e testing og linting? Bare lukk isåfall, bare må ha tasks for det om ikkjeee

**Comment by AlmaasAre** [comment]
e2e har egen task, linting er uppe
