### ISSUE TITLE
Sett opp mysql connector 

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-api#12]
Som #6

**Comment by kennethlynne** [comment]
http://docs.strongloop.com/display/public/LB/Connect+your+API+to+a+data+source

**Comment by AlmaasAre** [comment]
Trenger vi begge deler? Har satt opp mongodb nå!

**Comment by kennethlynne** [comment]
Om det er null oppstartstid så er det jo greit. Det er kanskje bare å legge til en datasource/config, og ikke noe mer? Da er det jo lett nok å ta det as needed. Lukker for nu!
