### ISSUE TITLE
Sett opp hosting av løsningen

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-api#13]
Nodejitsu, heroku, azure, aws? Vi må ha et sted å fettalett kunne deploye til. La oss diskutere litt hvilke alternativervi burde velge @AlmaasAre

**Comment by kennethlynne** [comment]
Det er kanskje ikke så mye å vinne på å ha det dockerifisert #17?

**Comment by kennethlynne** [comment]
Relatert: https://github.com/EdtechFoundry/edtech-seed-project-api-deprecated/issues/20

**Comment by AlmaasAre** [comment]
Stemmer for heroku. Fungerer godt, og man kan enkelt legge til addons for hver site. Addons som database, newrelic, logging osv osv.

**Comment by AlmaasAre** [comment]
Close @kennethlynne ?

**Comment by kennethlynne** [comment]
Ja, som fean
