### ISSUE TITLE
Sett opp CI

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-api#14]
Gjør det mulig å sjekke inn koden på github master branch, og få det øyeblikkelig deployet til et staging miljø om tester kjører.

Deretter kanskje kjøre e2e tester mot staging miljø og til slutt rulle ut til prod om disse kjører.

Litt usikker på hvordan vi skal håndtere migrering av databaser og slikt, men det tar vi i en egen task (#15).

**Comment by kennethlynne** [comment]
TeamCity?

**Comment by AlmaasAre** [comment]
Codeship for alle penga.

one testing environment and one production environment for now : )

**Comment by AlmaasAre** [comment]
https://github.com/ramr/strongloop-buildpack


sett opp deploy til heroku med buildpack

**Comment by kennethlynne** [comment]
Ke, skjønner ikke status her nå. Det gjenstår å sette opp det for å få CI?

**Comment by AlmaasAre** [comment]
Ja, altså, strongloop har sin egen metode for å bygge/kjøre applikasjoner på. Så må recreate appen på heroku med buildpacken til Strongloop..

**Comment by AlmaasAre** [comment]
evt. bytte buildpack med heroku CLI
