### ISSUE TITLE
Sett opp en docker VM 

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-api#17]

**Comment by kennethlynne** [comment]
Er det noe å vinne på å legge det på docker?

En utviklings VM med alt satt opp kanskje, men vi blir AFAIK å bruke MySQL, MongoDB og ElasticSearch osv as a service, så ikke noe vits for prodmiljø.

Det er kanskje ikke så mye å tjene på en VM da? 
En VM må ha git, node og npm bare AFAIK.

**Comment by kennethlynne** [comment]
Yay or nay @AlmaasAre ? I lean towards nay. Om du er enig kan du lukke issue, så kan vi revurdere senere.

**Comment by AlmaasAre** [comment]
Jaaa. Heroku f. Eks løser jo alt av monitorering, oppstart/nedetid, clustering, flere prosesser osv. 

Strongloop sin performance monitor eller hva det heter er meget good den også da. Men må gjøre mye selv. I vote nay for now! I ikke hatt store problemer med Heroku enda så..
