### ISSUE TITLE
Sett opp logging

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-api#20]
New Relic?

**Comment by kennethlynne** [comment]
Are sa en gang: https://www.runscope.com/ ?

Runscope ser bra ut når det gjelder smoketests av API og generell monitorering osv.

http://newrelic.com/ ?

NewRelic er jo NewRelic.. En megaløsning som løser det meste. Monitorering, større innsikt i hvordan API'et brukes.

Ref: https://github.com/EdtechFoundry/edtech-seed-project-api-deprecated/issues/15

**Comment by AlmaasAre** [comment]
New relic!

**Comment by AlmaasAre** [comment]
Med paper trail - plugin ++
