### ISSUE TITLE
Sett opp to-stegs autentisering og/eller passwordless

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-api#4]
Vi må ha opp mulighet for to-stegs autentisering eller passwordless. Et godt alternativ er å integrere mot google authcode app så man kan generere koder på mobilen? Let's discuss!
https://github.com/strongloop/loopback-example-two-factor 
www.passwordless.net

**Comment by AlmaasAre** [comment]
Lav pri i første omgang? Får opp Auth og tilgangsstyring først, og så legger vi til sikrere Auth og flere innloggingsmetoder etterhvert? 

Tror det er AD vi bør se på i første omgang. Det er det skolene bruker iallfall. Bare vi får tilgang til skolens ad-server eller Identityserver e.l er det jo Done,! e9?

**Comment by kennethlynne** [comment]
Lav pri indeed, og godt mulig AD må prioriteres først, lets decide and throw dice JIT
