### ISSUE TITLE
Sett opp E2E tester med jasmine + supertest

### ISSUE THREAD

**Issue by kennethlynne** [EdtechFoundry/edtech-seed-project-api#8]
Men supertest  + jasmine == aweseomeness
https://github.com/jasmine/jasmine-npm/issues/31

**Comment by kennethlynne** [comment]
@AlmaasAre enige om http://frisbyjs.com/ ?

**Comment by kennethlynne** [comment]
http://vrest.io/

**Comment by kennethlynne** [comment]
http://stackoverflow.com/questions/24410629/unit-testing-remote-methods-of-a-strongloop-loopback-io-model

**Comment by kennethlynne** [comment]
#23 må og på plass da

**Comment by kennethlynne** [comment]
https://github.com/strongloop/loopback-testing - er loopbacks egen tilnærming til å få til mye av det samme

**Comment by kennethlynne** [comment]
https://github.com/vowsjs/api-easy

**Comment by AlmaasAre** [comment]
Har prøvd å implementer Frisbyjs, uten hell. Har ingen teardown-metoder ellernoe. Kaster exceptions på expectene, istedenfor å la jasmine ta hånd om de. 

På forrige API-prosjekt, circumventa jeg det ved å bruke:

```
 javascript

exec('jasmine-node e2e/', function (err, stout/*, stderr*/) {

    if (err) {
      gulp.$log.error(stout);
    }
    else {
      gulp.$log.success(stout);
    }

    server.kill();
    return done(err);
  });

```

Det funka jo det, men forventer at man har jasmine-node globalt og ser messy ut.

Heller mot å bruke https://github.com/visionmedia/supertest altså. Ser veldig ryddig ut, enkelt å starte opp server. barambim barambom: http://stackoverflow.com/a/24465669/1574396

Det andre alternativet er: http://www.michaeldausmann.com/2015/01/integration-testing-restful-endpoint.html

Men har hørt fra deg at mocha er litt krøkkete, og vi bruker jo jasmine FE.. Greit å være konsistente der..

**Comment by AlmaasAre** [comment]
Men supertest  + jasmine == aweseomeness
https://github.com/jasmine/jasmine-npm/issues/31

**Comment by kennethlynne** [comment]
Ja det syntes jeg at vi skal gå for!

**Comment by kennethlynne** [comment]
Ey, wait a second, sett godt nok på loopback sine greier? https://github.com/strongloop/loopback-testing

**Comment by AlmaasAre** [comment]
Yeah, ser meget alright ut, men bruker mocha tho!

Det er det som ser absolutt lettest ut da. Den Databuikldern kan vi jo bruke uansett. Men når man jobber med Loopback, hvorfor ikke gjør det på loopback-måten..? 

Enig at vi bruker loopback-testing da?

**Comment by AlmaasAre** [comment]
#29
